Сайт pet7.ru работает по протоколу HTTPS.

Структура сайта имеет header,main content и footer
https://1drv.ms/i/s!Ah-DC-HuoC8ukCEayMAxQexATsR0?e=WDaWaQ
https://1drv.ms/i/s!Ah-DC-HuoC8ukB_n1bb_F3hJyzLF?e=Yl6XFN
https://1drv.ms/i/s!Ah-DC-HuoC8ukCBMAYaaMZCmWG2R?e=KU31Qm



