# Сайт pet7.ru работает по протоколу HTTPS.

# Структура сайта имеет header,main content и footer
- https://1drv.ms/i/s!Ah-DC-HuoC8ukCEayMAxQexATsR0?e=WDaWaQ
- https://1drv.ms/i/s!Ah-DC-HuoC8ukB_n1bb_F3hJyzLF?e=Yl6XFN
- https://1drv.ms/i/s!Ah-DC-HuoC8ukCBMAYaaMZCmWG2R?e=KU31Qm

# Внесите не менее 3 изменений на страницу с помощью инструмента разработчика и представьте скриншоты было/стало.
- До изменении:
- https://1drv.ms/i/s!Ah-DC-HuoC8ukCLKxe3jNO9oXvTy?e=oUkwLz
- После изменений:
- https://1drv.ms/i/s!Ah-DC-HuoC8ukCN3ARtyVe7CsUPf?e=WNpr1X

# Создайте прототип низкой детализации.
file:///C:/Users/bychk/OneDrive/Рабочий%20стол/Новая%20папка/Wireframe.cc%20–%20the%20go-to%20free,%20online%20wireframing%20tool..html

# PS:Все скриншоты в одном файле.




