Сайт pet7.ru работает по протоколу HTTPS.

Структура сайта имеет header,main content и footer
c:\Users\bychk\Downloads\2023-07-08_14-01-11.png
c:\Users\bychk\Downloads\2023-07-08_14-23-42.png
c:\Users\bychk\Downloads\2023-07-08_14-30-21.png



