1. Определите, на каком протоколе работает сайт youtube.com.
https://1drv.ms/i/s!Ah-DC-HuoC8ukDmKv8oPbsz4-EWh?e=ialYEa

2. Создайте файл 2_analyze.txt, в котором проанализируйте структуру страницы сайта https://ru.wikipedia.org/.
 Шапка сайта включает в себя:
- Название,Логотип сайта;
- Создание учётной записи,Вход по имеющейся уч.записи,Страница Уч-ка для моего ID;
- Окно поиска;
- Заглавная с Обсуждением,Прочтением,Просмотром кода И Историей;
 - Порталы,Справка,Создать статью.
 Подвал содержит:
- Места расположения Фонда Википедии:
 - Перечисление других проектов;
- Лицензии,Информация о регистрации товарного знака сайта;
- Условия использования,Политика конфедициальности,Описание сайта;
- Отказ от ответственности,Каналы связи,Кодекс поведения;
- Мобильная версия,Разработчики,Статистика,Заявления о куки.
 Контент расположен посредине(между Шапкой и Подвалом).Содержит:
- Статьи:Избранные,Новые,Хорошие или Лучшие:
(с возможностью краткого и полного прочтения,Обсуждением);
- Текущие События (с расширением);
- Списки(разного содержания);
- События текущего дня(с возможностью подробного прочтения);
- Изображение Дня;
- Совместная Работа Недели.
 Дополнительные Элементы:
- Расположны слева(практичиски во всю длину сайта).Состоит:
 - Заглавная страница,Участие,Инстументы;
 - Печать/Экспорт,В других проектах,На других языках;
 Т.Е.состовляет все содержание сайта.

3. Внесите не менее 10 изменений на страницу любой статьи сайта https://ru.wikipedia.org/, с помощью инструмента разработчика.
 До Изменения:
https://1drv.ms/i/s!Ah-DC-HuoC8ukDqS6PueuRIFit_z?e=rSHTzc.
 После Изменения:
https://1drv.ms/i/s!Ah-DC-HuoC8ukDtGhE8LslO0cUQ-?e=FKXSph

4. Создайте прототип низкой детализации сайта https://dzen.ru/ с помощью сайта https://wireframe.cc/.
https://1drv.ms/i/s!Ah-DC-HuoC8ukDJP3hPyFRTua01h?e=fOkPd1.

Все скриншоты в одном файле.



